# firebase deploy --only dataconnect
# firebase dataconnect:sdk:generate

query MeetingsByConsultantId($consultantId: String!) @auth(level: USER) {
  user(id: $consultantId) @redact {
    id @check(expr: "this == auth.uid", message: "Disallowed operation")
  }
  meetings(where: { consultant: { id: { eq: $consultantId } } }) {
    id
    member {
      id
      displayName
      email
      photoUrl
    }
    calendlyEventUri
    endTime
    startTime
    status
    stripeCheckoutSessionId
    stripeProductId
  }
}

query AllConsultantProfilePicturesAndIds @auth(level: USER) {
  users(where: { role: { eq: "consultant" } }) {
    id
    photoUrl
  }
}

query GetMeeting($meetingId: UUID!) @auth(level: NO_ACCESS) {
  meeting(id: $meetingId) {
    id
    member {
      id
    }
    consultant {
      id
    }
  }
}

mutation UpdateMeetingStatus($meetingId: UUID!, $status: String!)
@auth(level: NO_ACCESS) {
  query {
    meeting(id: $meetingId) @redact {
      member {
        id @check(expr: "this == auth.uid", message: "Disallowed operation")
      }
    }
  }
  meeting_update(id: $meetingId, data: { status: $status })
}

mutation UpdateMeetingCalendlyScheduleUrl(
  $id: UUID!
  $calendlyScheduleUrl: String!
) @auth(level: USER) {
  meeting_update(id: $id, data: { calendlyScheduleUrl: $calendlyScheduleUrl })
}

mutation UpdateUserProfilePicture($photoUrl: String!, $id: String!)
@auth(level: NO_ACCESS) {
  user_update(id: $id, data: { photoUrl: $photoUrl })
}

mutation InsertUser(
  $displayName: String!
  $email: String!
) @auth(level: USER) {
  user_insert(
    data: {
      id_expr: "auth.uid"
      displayName: $displayName
      email: $email
      role: "member"
    }
  )
}

query GetUser($id: String!) @auth(level: USER) {
  user(id: $id) {
    id @redact @check(expr: "this == auth.uid", message: "Disallowed operation")
    displayName
    email
    role
    createdAt
    photoUrl
    bio
    updatedAt
  }
}

query MeetingsForCurrentUser @auth(level: USER) {
  meetings(where: { memberId: { eq_expr: "auth.uid" } }) {
    id
    consultant {
      id
      displayName
    }
    endTime
    startTime
    status
    stripeCheckoutSessionId
    stripeProductId
    calendlyScheduleUrl
    calendlyEventUri
  }
}
